### ISSUE TITLE
"rails generate couchbase:view DESIGNDOCNAME VIEWNAME" breaks save_design_doc

### ISSUE THREAD

**Issue by mtparet** [couchbase/couchbase-ruby-model#5]
I obtain:

```
Couchbase::Error::HTTP: failed to execute HTTP request (key="_design/coupon_code_c", status="400" (Bad Request), error=0x00)
    from /ruby-1.9.3-p327/gems/couchbase-1.2.1/lib/couchbase/bucket.rb:165:in `continue'
    from /ruby-1.9.3-p327/gems/couchbase-1.2.1/lib/couchbase/bucket.rb:165:in `save_design_doc' 
```

After removing comments around the function in map.js, it's working again.

**Comment by jdittric** [comment]
I'm having the same issue, eliminating all comments as above worked for me as well.

**Comment by avsej** [comment]
The issue has been fixed http://review.couchbase.org/24688 /cc @ingenthr
